- name: Inject PubKey into a Local Server
  hosts: localhost
  gather_facts: True
  connection: local
  become: yes
  become_method: sudo
  
  tasks:
  - name: Inject PubKey into Local Server 
    shell: echo "{{ pubkey }}" >> /root/.ssh/authorized_keys
