- name: Inject PubKey into a Local Server
  hosts: localhost
  gather_facts: True
  connection: local
  
  tasks:
  - name: Create authorized_keys file
    command: touch /var/lib/awx/.ssh/authorized_keys
    
  - name: Inject PubKey into Local Server 
    command: echo "{{ pubkey }}" >> /var/lib/awx/.ssh/authorized_keys
